### ISSUE TITLE
Create dot and slash routing; split producer into a separate object (like it is done with the consumer).

### ISSUE THREAD

**Issue by WiZeYAR** [G-USI/asyncapi-python#6]
Basically, if I have:

```yaml
asyncapi: "3.0.0"
info:
  title: Client part of the Ping-Pong service example
  version: 1.0.0

operations:
  /service/messages/get:
    action: send
    ...
  service.messages.get:
    action: receive
    ...
```

The generated app must have:
```python
app.producer.service.messages.get(...)

@app.consumer.service.messages.get(...)
```

If it causes routing collisions, it results in a compile error
